import type { Transformation } from "./queries";

export const fallbackTransformations: Transformation[] = [
  {
    id: "fallback-1",
    slug: "alex-strength",
    name: "Alex",
    age: "29",
    occupation: "Software Engineer",
    note: "Lost 15kg and built lasting strength with a consistent training routine.",
    quote: "This program helped me become stronger, more confident, and energized every day.",
    image_url:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
    before_image: null,
    after_image: null,
    duration_months: 4,
    program: "Strength & Fat Loss",
    stats: [],
    goals: [],
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "fallback-2",
    slug: "jordan-transformation",
    name: "Jordan",
    age: "34",
    occupation: "Marketing Director",
    note: "Dropped two dress sizes and gained confidence with a smart nutrition plan.",
    quote: "I finally feel like my body matches my goals.",
    image_url:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80",
    before_image: null,
    after_image: null,
    duration_months: 5,
    program: "Lifestyle Reset",
    stats: [],
    goals: [],
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "fallback-3",
    slug: "maria-coaching",
    name: "Maria",
    age: "27",
    occupation: "Teacher",
    note: "Built strength and energy while balancing a busy schedule.",
    quote: "The training plan made fitness simple and sustainable.",
    image_url:
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80",
    before_image: null,
    after_image: null,
    duration_months: 3,
    program: "Performance Coaching",
    stats: [],
    goals: [],
    featured: true,
    created_at: new Date().toISOString(),
  },
];
